---
title:
- type: main
  text: York Factory to the Blackfeet Country
- type: subtitle
  text: The Journal of Anthony Hendry, 1754-55
- type: extended
  text: The Royal Society of Canada, 1908
creator:
- role: author
  text: Anthony Hendry
- role: editor
  text: Lawrence J. Burpee
rights: © 2021 Public domain
...
